version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - htmlzip

build:
  os: ubuntu-22.04
  apt_packages:
    - graphviz
  tools:
    python: "3.12"
  jobs:
    post_install:
      - python -m pip install 'uv>=0.2.0'
      - python -m uv pip install -c .constraints/py3.12.txt -e .[doc]
