#!/bin/bash
# cspell:ignore nbextension serverextension
set -e
jupyter nbextension install --py hide_code --user
jupyter nbextension enable --py hide_code --user
jupyter serverextension enable --py hide_code --user
